### ISSUE TITLE
பிலோ இருதயநாத் நூல்கள்

### ISSUE THREAD

**Issue by tshrinivasan** [KaniyamFoundation/CreativeCommonsAnnouncements#16]
Philo Irudhayanath

https://ta.wikipedia.org/s/1p21

http://www.sramakrishnan.com/?p=546

இவரது நூல்களை சேகரிக்க வேண்டும்.

**Comment by gnuanwar** [comment]
### பிலோவின் புத்தகங்கள்

**1.1961, ஆதிவாசிகள், கலைமகள் காரியாலயம், சென்னை.** hard copy 
2.  1979, மேற்கு மலைவாசிகள், மல்லிகை பதிப்பகம், சென்னை
3.  1967, காட்டில் என் பிரயாணம், இளங்கோ பதிப்பகம், சென்னை
4.  1967, அறிவியல் பூங்கா, இளங்கோ பதிப்பகம், சென்னை
5.  1984, காட்டில் மலர்ந்த கதைகள், வானதி பதிப்பகம், சென்னை
**6.  1984, காட்டில் கண்ட மர்மம், வானதி பதிப்பகம், சென்னை**
**7.  1985, யார் இந்த நாடோடிகள், வானதி பதிப்பகம், சென்னை**
8.  1978, பழங்குடிகள், தமிழ் செல்வி நிலையம், சென்னை
**9.  1977, ஆதிவாசிகள் மறைந்த வரலாறு, தமிழ் செல்வி நிலையம், சென்னை** tuv
10.  1967, இமயமலை வாசிகள், மல்லிகை பதிப்பகம், சென்னை
**11.  1989, கேரளா ஆதிவாசிகள், வானதி பதிப்பகம், சென்னை** tuv & hard copy
12.  1991, நீலகிரி படுகர்கள், வானதி பதிப்பகம், சென்னை
**13.  கொங்கு மலைவாசிகள், தென்றல் நிலையம், சிதம்பரம் hard copy**
14.  கோயிலும் குடிகளும், தென்றல் நிலையம், சிதம்பரம்
15.  தமிழக ஊர்களின் தனிச்சிறப்பு, தென்றல் நிலையம், சிதம்பரம்
16.  குறிஞ்சியும் நெய்தலும், தென்றல் நிலையம், சிதம்பரம்
17.  கோயிலைச் சார்ந்த குடிகள், தென்றல் நிலையம், சிதம்பரம்
**18. யூதர்கள் ஆதிவாசியானது எப்படி** hard copy 
19. நீலகிரி படகர்கள்
**20. பயணம் ஒரு கலை,ஏமாந்தால்?** hard copy 
**21. காட்டில் கண்ட மர்மம்**hard copy 
22. குறிஞ்சியும் நெய்தலும்
23. கோயிலும் குடிகளும்
24. தமிழ் மலையாளிகள்
25. மக்கள் வணங்கும் ஆலயம்
26. தமிழில் அச்சான முதல் நூல்
27. காடு கொடுத்த ஏடு
**28.எங்கே நிம்மதி எங்கிருந்து வந்தோம் எங்கே போகிறோம்?** hard copy 

highlighted books are avialble with us no 28 book is avialble with nelagiri venugopal

**Comment by gnuanwar** [comment]
### தவறுகளில் இருந்து பாடம் கற்போம் 

நேற்று 17/07/19 அன்று பிலோவின் இளைய சகோதரர் மகன் திரு மனோ அவர்களிடம் creative commons அனுமதி (ஆங்கிலம்,தமிழில் தட்டச்சு செய்த) கடிதத்தை கையோப்பம் வாங்க  மாலை 7மணி அளவி்ல் சென்றேன் மனோ அவர்களின் துணைவியார் ஐரின் அந்த கடிதத்தை படித்துவிட்டு அதில்  commercial என்று குறிப்பிடள்ளது அதனால் இதனை நாங்கள் கையேழுத்து போட மாட்டோம் என்று இதில் இந்த வார்த்தை யை எடுத்தால் கையேழுத்து போடலாம் என்று சொன்னார் ஆனால் பிலோவின் மற்ற வாரிசுகள் கையேழுத்து இட எங்களுக்கு ஆட்ச்சேபனை இல்லை என்று கூறினார் commercial பற்றி மற்றும் cc பற்றிய விளக்கம் கொடுக்கபட்டும் அவர்கள் நமது விளக்கத்தை ஏற்க்கவில்லை இந்த கடிதம் [creative commons      ](https://creativecommons.org/licenses/by-sa/4.0/)   

அதன் அடிப்படையில் மட்டுமே தயாரிக்கபட்டது என்ற விளக்கத்தை கொடுத்தும் அவர்கள் ஏற்க்கவில்லை 

மேலும் 09/07/19 அன்று மனோ மற்றும் அவரின் துணைவியாரிடம் அனுமதி கடிதத்தின் மாதிரியை காட்டி அவர்கள் சொன்ன திருத்தங்களை செய்துவிட்டுதான் நாம் அனுமித கடிதத்தை கையேழுத்து வாங்க சென்றோம் இதனை பற்றி வினா எழுப்பினால் அன்று நான் படிக்கவில்லை என்று சொல்கிறார்

CC-BY-SA உரிமையில் வெளியிட்டால் மட்டுமே அச்சு நூல்களை Scan/OCR/Proofread/CoverImage/Ebook making செய்து இலவச மின்னூலாக வெளியிட முடிவெடுத்துள்ளோம். 

பிலோ நூல்களை CC-BY-SA உரிமையில் பெறுவது எப்படி என்று ஆய்ந்து வருகிறோம்.



படைப்பாக்க பொதுமங்கள் உரிமை தமிழ் மற்றும் ஆங்கிலத்தில்  
https://bit.ly/2Yat9yx

https://bit.ly/1upaQv7
