### ISSUE TITLE
எம் .எஸ் உதயமூர்த்தி-நூல்கள்,உரைகளை படைப்பாக்க பொதுமங்கள் அனுமதி சந்திப்பு 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/CreativeCommonsAnnouncements#22]
எம் .எஸ் உதயமூர்த்தி நூல்கள்,உரைகளை ஆவணபடுத்த  நீண்ட தேடலுக்கு பின்பு அவரின் அண்ணன் மகன் ஜெகதீசன் அவர்களை அவரது சென்னை திருவானமயூர் இல்லத்தில் சந்தித்து அவரது உரைகளை ஆவணபடுத்தல் பற்றிய விரிவாக மேசினேன் கணியம் மற்றும் பிரி தமிழ் இபுக்ஸ் தளம் பற்றி சொல்லபட்டது. விரைவில் அவரது நூல்கள் மற்றும் உரைகளை பற்றிய அறிவிப்புகளை வெளியிட ஆவண செய்வதாக உறுதி அளித்தார்
  https://ta.wikipedia.org/wiki/%E0%AE%8E%E0%AE%AE%E0%AF%8D._%E0%AE%8E%E0%AE%B8%E0%AF%8D._%E0%AE%89%E0%AE%A4%E0%AE%AF%E0%AE%AE%E0%AF%82%E0%AE%B0%E0%AF%8D%E0%AE%A4%E0%AF%8D%E0%AE%A4%E0%AE%BF
![photo_2019-08-26_21-03-52](https://user-images.githubusercontent.com/38220354/63703118-f62db500-c845-11e9-9b88-401450a6c2a7.jpg)

**எழுதிய நூல்கள்**

1. எண்ணங்கள் (சனவரி 1976)
2. மனம் பிரார்த்தனை மந்திரம்
3. தலைவன் ஒரு சிந்தனை
4. உயர்மனிதனை உருவாக்கும் சிந்தனைகள்
5. பிரச்சனைகளுக்கு முடிவு காண்பது எப்படி?
6. ஆத்ம தரிசனம்
7. தட்டுங்கள் திறக்கப்படும்
8. நாடு எங்கே செல்கிறது?
9. நீதான் தம்பி முதலமைச்சர்
10. சிந்தனை தொழில் செல்வம்
11. மனித உறவுகள்
12. நெஞ்சமே அஞ்சாதே நீ
13. தன்னம்பிக்கையும் உயர்தர்ம நெறிகளும்
14. ஜேம்ஸ் ஆலனின் வாழ்க்கையை அமைக்கும் எண்ணங்கள்
15. வெற்றிக்கு முதற்படி
16. உலகால் அறியப்படாத ரகசியம்
17. சாதனைக்கோர் பாதை
18. சொந்தக் காலில் நில்
19. வெற்றி மனோபாவம்

![photo_2019-08-26_21-04-00](https://user-images.githubusercontent.com/38220354/63703119-f62db500-c845-11e9-9c59-e5abeb55d0fa.jpg)

**Comment by gnuanwar** [comment]
ms udhyamurthy book in mp3

![image](https://user-images.githubusercontent.com/38220354/63707367-6260e680-c84f-11e9-8b35-6265ffc1ee7a.png)
https://groups.google.com/forum/m/#!topic/alt.religion.hindu/mdQtipX3BE8

**Comment by gnuanwar** [comment]
### எண்ணங்கள் புத்தக மதிப்புரை goodreads
![image](https://user-images.githubusercontent.com/38220354/63707837-7bb66280-c850-11e9-8f2a-2762680465c4.png)

**Comment by gnuanwar** [comment]
### எண்ணங்கள் பெயரில் ஒரு முக நூல் பக்கம் 

பலர் எம் .எஸ் உதயமூர்த்தி நினைவுகளை பகிர்ந்நு whatsapp group - அவரை பற்றிய கருத்துகளை பகிர்ந்துள்ளாரகள்
![image](https://user-images.githubusercontent.com/38220354/63708464-2aa76e00-c852-11e9-8c92-eaf9b6bb57ff.png)

**Comment by gnuanwar** [comment]
### எம் .எஸ் உதயமூர்த்தி பும்மகங்கள் ஒலி வடிவில் youtube இணைப்புகள்

- எண்ணங்கள் அனைத்து பாகங்களும் 

https://www.youtube.com/channel/UCkuWoF4EF7kBr97t52nq6mA/search?query=Dr.+MS+udayamurthy

**Comment by gnuanwar** [comment]
### எம் .எஸ் உதயமூர்த்தி மேடை பேச்சு

https://www.youtube.com/watch?v=kg0QJzYKFNI

**Comment by gnuanwar** [comment]
### Udhayamoorthy motivational interview

https://www.youtube.com/watch?v=yzE0j6TsP8I

![image](https://user-images.githubusercontent.com/38220354/63709053-ab1a9e80-c853-11e9-8385-ea8b37ada4d5.png)

Dr M.S.Udhayamoorthy motivatinal song 

https://www.youtube.com/watch?v=vewQTjzDCqk

**Comment by gnuanwar** [comment]
### எண்ணங்கள் book in scribid
https://www.scribd.com/document/356004303/213829372-Ennangal-by-m-s-Udhayamurthi-%E0%AE%8E%E0%AE%A3-%E0%AE%A3%E0%AE%99-%E0%AE%95%E0%AE%B3

**Comment by gnuanwar** [comment]
எம்.எஸ் உதயமூர்த்தி அவர்களின் புதல்வர் சித்தார்த்தன் அமேரிக்கவாவில் இருந்து சென்னை வந்துள்ளார் நளை அமேரிக்கா செல்வதால் அவரிடம் புத்தகங்களுக்கான அனுமதி கடித்த்தை dunzo app மூலம்  அவரிடம் சேர்க்கபட்டது. மின் அஞ்சல் மூலம் கடிதம் அனுப்பட்டது விரைவில் அனுமதி கையழுத்து ஆகும்.

**Comment by gnuanwar** [comment]
01.012020 இன்று  மறைந்த எம்.எஸ் உதயமூர்த்தி அவர்களின் அண்ணன் மகன் ஜெகதீசன் அவர்களிடமிருந்து creative commons அறிவிப்பு கடிதத்தை பெற்றேன் சமிபத்தில் அமேரிக்காவில் இருந்து சென்னைக்கு வந்த  சித்  எம்.எஸ் உதயமூர்த்தி அவர்களின் மூத்த மகன் அனுமதி கடிதத்தை கையேழுத்து போட்டு தந்தார். இந்த வருடத்திதின் முதல் creative commons  அனுமதி கடிதம் 


https://www.facebook.com/gnuanwar/posts/10218815841899025

**Comment by gnuanwar** [comment]
ms udhayamurthy deceleration 
[msud-dec.pdf](https://github.com/KaniyamFoundation/CreativeCommonsAnnouncements/files/5582428/msud-dec.pdf)

**Comment by gnuanwar** [comment]
![msud-dec-page-001](https://user-images.githubusercontent.com/38220354/99955272-0e261880-2daa-11eb-8df5-9c5cb06f288f.jpg)

**Comment by gnuanwar** [comment]
இன்று ரோஜா முத்தையா நூலகத்தில் உள்ள உதயமூரத்தியின் நூல்களையும் ஒளிவருட  தந்துள்ளார்கள் விரைவில் archive தளத்தில் ஏற்றப்படும் @tshrinivasan இதற்க்கான காப்புரிமை தகவலை scribe மென்பொருளில் குறிப்பிட என்ன வழி custom வழியே குறிப்பிடலாம் ஆனால் காப்புரிமையை தேர்வு செய்யும் முறையில் இருந்தால் சிறப்பு

**Comment by tshrinivasan** [comment]
எம். எஸ் உதயமூர்த்தி - வருடப்பட்ட மின்னூல்கள் இங்கே உள்ளன.

https://archive.org/search.php?query=creator%3A%22Utayamu%CC%84rtti%2C+Em.+Es%22
