### ISSUE TITLE
கோவை ஞானி புத்தகங்கள் படைப்பாக்க பொதுமங்கள் அறிவிப்பு 

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/CreativeCommonsAnnouncements#5]
17/03/19 சனி
FreeTamilEbooks.com தளத்திற்க்கு புத்தகங்களின் அனுமதி பெற கோயமுத்தூர் பயணம் மிகவும் வெற்றிகரமாக அமைந்தது. கோவை ஞானி அவர்களுக்கு கி.கா உரிமை,கணியம் அறக்கட்டளை பற்றிய விரிவான  விளக்கம் ஒளி,ஒளி கோப்பாக காண்பிக்கபட்டது. அது பற்றிய ஜயங்களுக்கு உடன் பதில் அளித்தேன் .  மிகவும்   நல்ல ஒத்துழைப்பை தந்தார் . அய்யா அவர்களின் உதவியாளர் திருமதி மீனா அவர்கள் பணிக்கு வரவில்லை என்பதால் 18/3/19 இது பற்றிய அறிவிப்பை தருகிறேன் என்று உறுதி அளித்தார்.

18/03/19 ஞாயிறு 

கி.கா உரிமை பற்றிய கடிதம் அவரின் உதவியாளர் மீனா அவர்களால் படித்து காட்டபட்டது. முதல் கட்டமாக அவரின் எட்டு புத்தகங்களை கொடுத்தார். புத்தகங்கள் உடன் @gurulenin அவர்களுக்கு தூதஞ்சல் அனுப்பட்டது. அய்யா சில புத்தகங்களை உடன் வெளியிட  வேண்டுகோள் வைத்தார். அவை முன்னுரிமை அடிப்படையில் வெளியிடப்படும். அவரின் ஒரு நூலில், நூல்கள் யாவும் ஒரு அறக்கட்டளை அமைத்து பாதுகாக்கவேண்டும் என்ற ஆசையை தெரிவித்துள்ளார். அவரின் எந்த நூலை படித்தாலும் நாம் மிகவும் ஒன்றி போய் தெளிந்த நீரோடை ஒடுவது போல ஒரு வாசிப்பு அனுபவத்தை நாம் எல்லோரும் பெற சிறிது நாள் காத்திருக்க வேண்டும்.
![kovaignani_anwar](https://user-images.githubusercontent.com/38220354/54979924-72d41300-4fca-11e9-9c67-8f0f82429337.jpg)

மேலும் கி.கா உரிமையில் மற்ற எழுத்தாளர்களும் அறிவிக்க வேண்டும் என்ற அறிவிப்பை தர வேண்டும் என்பதை காணொளியில் தெரிவித்தார்.
![gnani_cc](https://user-images.githubusercontent.com/38220354/54980023-aa42bf80-4fca-11e9-9269-287870973fa2.jpg)

அவர் கொடுத்த நூல்களின் பட்டியல்  

| எண் |நூல் | வெளியான ஆண்டு |
|---|--------|---------------------|
| 1 |மார்க்சியமும் தமிழ் இலக்கியமும் | 1988 |
| 2 |தமிழகத்தில் பண்பாட்டு நெருக்கடிகள் | 1994 |
| 3 |எண்பதுகளில் தமிழ் நாவல்கள் | 1994 |
| 4 |படைப்பியல் நோக்கில் தமிழிலக்கியம் |
| 5 |தமிழில் நவீனத்துவம் பின்நவீனத்துவம் | 1997 |
| 6| நானும் என் தமிழும் | 1999 |
| 7 |தமிழன் வாழ்வும் வரலாறும் | 1999 |
| 8 |தமிழில் படைப்பியக்கம் | 1999 |
| 9 |மறுவாசிப்பில் தமிழ் இலக்கியம் | 2001 |
| 10 |எதிர் எதிர் கோணங்களில் | 2002 |
| 11 |மார்க்சிய அழகியல் | 2002 |
| 12 |கவிதையிலிருந்து மெய்யியலுக்கு | 2002 |
| 13 |தமிழ் தமிழர் தமிழ் இயக்கம் | 2003 |
| 14 |தமிழ் நாவல்களில் தேடலும் திரட்டலும் | 2004 |
| 15 |வரலாற்றில் தமிழர் தமிழ் இலக்கியம் | 2004 |
| 16 |தமிழ் வாழ்வியல் தடமும் திசையும் | 2005 |
| 17 |தமிழன்பன் படைப்பும் பார்வையும் | 2005 |
| 18 |வள்ளுவரின் அறவியலும் அழகியலும் | 2007 |
| 19 |தமிழ் மெய்யியல் அன்றும் இன்றும் | 2008 |
| 20| நெஞ்சில் தமிழும் நினைவில் தேசமும் | 2009 |
| 21 |செவ்வியல் நோக்கில் சங்க இலக்கியம் | 2010 |
| 22 |தமிழிலக்கியம் இன்றும் இனியும் | 2010 |
| 23 |வானம்பாடிகளின் கவிதை இயக்கம் | 2011 |
| 24 |ஏன் வேண்டும் தமிழ்த் தேசியம் | 2012 |
| 25 |அகமும் புறமும் புதுப்புனல் | 2012 |
| 26 |அகமும் புறமும் தமிழ்நேயம் | 2012 |
| 27 |ஞானியின் எழுத்துலகம் | 2005 |
| 28 |ஞானியோடு நேர்காணல் | 2012 |
| 29 |மார்க்சியத்திற்கு அழிவில்லை | 2001 |
| 30 |மார்க்சியமும் மனித விடுதலையும் | 2012 |
| 31 |இந்திய வாழ்க்கையும் மார்க்சியமும் | 1975 |
| 32 |மணல் மேட்டில் ஓர் அழகிய வீடு | 1976 |
| 33 |கடவுள் ஏன் இன்னும் சாகவில்லை | 1996 |
| 34 |நானும் கடவுளும் நாற்பது ஆண்டுகளும் | 2006 |
| 35 |கல்லிகை | 1995 |
| 36 |தொலைவிலிருந்து | 1989 |
| 37 |கல்லும் முள்ளும் கவிதைகளும் | 2012 |
| 38 |தமிழ்த் தேசியம் பேருரைகள் | 1997 |
| 39| அறிவியல் அதிகாரம் ஆன்மீகம் | 1997 |
| 40 |மார்க்சியத்தின் எதிர்காலம் | 1998 |
| 41 |படைப்பிலக்கியம் சில சிகரங்களும் வழித்தடங்களும் | 1999 |
| 42 |மார்க்சியத்தின் புதிய பரிமாணங்கள் | 1999 |
| 43 |விடுதலை இறையியல் | 1999 |
| 44 |இந்தியாவில் தத்துவம் கலாச்சாரம் | 2000 |
| 45 |மார்க்சியம் தேடலும் திறனாய்வும் | 2000 |
| 46 |நிகழ் நூல் திறனாய்வுகள் 100 | 2001 |
| 47 |பெண்கள் வாழ்வியலும் படைப்பும் | 2003 |
| 48 |நிகழ் இதழ் 29 |

**Comment by tha-uzhavan** [comment]
காலத்தையும் கடந்து நிற்கப் போகும், இந்த தமிழ் பணிக்கு என் வணக்கங்கள்.

**Comment by gnuanwar** [comment]
நன்றி த.உழவன்

**Comment by tshrinivasan** [comment]
| 1    மார்க்சியமும் தமிழ் இலக்கியமும்                   |   1988      |
|-----------------------------------------------------------------------------------|
| 2    தமிழகத்தில் பண்பாட்டு நெருக்கடிகள்               |    1994      |
| 3    எண்பதுகளில் தமிழ் நாவல்கள்                         |  1994     |
| 4    படைப்பியல் நோக்கில் தமிழிலக்கியம்      |
| 5    தமிழில் நவீனத்துவம் பின்நவீனத்துவம்            |      1997        |
| 6    நானும் என் தமிழும்                                |           1999   |
| 7    தமிழன் வாழ்வும் வரலாறும்                      |       1999    |
| 8    தமிழில் படைப்பியக்கம்                            |     1999    |
| 9    மறுவாசிப்பில் தமிழ் இலக்கியம்               |         2001     |
| 10    எதிர் எதிர் கோணங்களில்                        |          2002    |
| 11    மார்க்சிய அழகியல்                                 |          2002   |
| 12    கவிதையிலிருந்து மெய்யியலுக்கு           |            2002   |
| 13    தமிழ் தமிழர் தமிழ் இயக்கம்                    |          2003     |
| 14    தமிழ் நாவல்களில் தேடலும் திரட்டலும்  |               2004      |
| 15    வரலாற்றில் தமிழர் தமிழ் இலக்கியம்       |            2004      |
| 16    தமிழ் வாழ்வியல் தடமும் திசையும்         |               2005     |
| 17    தமிழன்பன் படைப்பும் பார்வையும்        |              2005      |
| 18    வள்ளுவரின் அறவியலும் அழகியலும்   |               2007    |
| 19    தமிழ் மெய்யியல் அன்றும் இன்றும்         |                2008       |
| 20    நெஞ்சில் தமிழும் நினைவில் தேசமும்    |                   2009     |
| 21    செவ்வியல் நோக்கில் சங்க இலக்கியம்    |                   2010       |
| 22    தமிழிலக்கியம் இன்றும் இனியும்             |              2010     |
| 23    வானம்பாடிகளின் கவிதை இயக்கம்        |                2011    |
| 24    ஏன் வேண்டும் தமிழ்த் தேசியம்              |              2012      |
| 25    அகமும் புறமும் புதுப்புனல்                    |              2012    |
| 26    அகமும் புறமும் தமிழ்நேயம்                  |                 2012    |
| 27    ஞானியின் எழுத்துலகம்                          |          2005   |
| 28    ஞானியோடு நேர்காணல்                         |             2012  |
| 29    மார்க்சியத்திற்கு அழிவில்லை                 |            2001     |
| 30    மார்க்சியமும் மனித விடுதலையும்          |                2012    |
| 31    இந்திய வாழ்க்கையும் மார்க்சியமும்       |                1975       |
| 32    மணல் மேட்டில் ஓர் அழகிய வீடு            |                1976     |
| 33    கடவுள் ஏன் இன்னும் சாகவில்லை          |              1996     |
| 34    நானும் கடவுளும் நாற்பது ஆண்டுகளும்             |     2006     |
| 35    கல்லிகை                                                               |  1995 |
| 36    தொலைவிலிருந்து                               |               1989 |
| 37    கல்லும் முள்ளும் கவிதைகளும்           |                  2012     |
| 38    தமிழ்த் தேசியம் பேருரைகள்               |                    1997    |
| 39    அறிவியல் அதிகாரம் ஆன்மீகம்          |                        1997     |
| 40    மார்க்சியத்தின் எதிர்காலம்                                 |                1998      |
| 41    படைப்பிலக்கியம் சில சிகரங்களும்  வழித்தடங்களும் |           1999        |
| 42    மார்க்சியத்தின் புதிய பரிமாணங்கள்              |             1999      |
| 43    விடுதலை இறையியல்                                     |                 1999 |
| 44    இந்தியாவில் தத்துவம் கலாச்சாரம்                   |          2000      |
| 45    மார்க்சியம் தேடலும் திறனாய்வும்                   |          2000      |
| 46    நிகழ் நூல் திறனாய்வுகள் 100               |                2001    |
| 47    பெண்கள் வாழ்வியலும் படைப்பும்                |       2003      |
| 48    நிகழ் இதழ் 29  |
