### ISSUE TITLE
எழுத்தாளர் ப.வா செல்லதுரை creative commons படைப்பாக்க பொதுமங்கள் அறிவிப்பு

### ISSUE THREAD

**Issue by gnuanwar** [KaniyamFoundation/CreativeCommonsAnnouncements#8]
இன்று நான் கலீல் ஜாக்கீர் உடன் எழுத்தாளர் [பவா செல்லதுரை](https://ta.wikipedia.org/wiki/%E0%AE%AA%E0%AE%B5%E0%AE%BE_%E0%AE%9A%E0%AF%86%E0%AE%B2%E0%AF%8D%E0%AE%B2%E0%AE%A4%E0%AF%8D%E0%AE%A4%E0%AF%81%E0%AE%B0%E0%AF%88) 
[பவா செல்லதுரை இணையதளம்](http://bavachelladurai.blogspot.com/)
அவர்களை சென்னையில் சந்தித்தோம் அவரிடம் கணியம் அறகட்டளை,பிரிதமிழ் இபுக்ஸ், பற்றி முழுமையாக எடுத்துரைக்கபட்டது மேலும் அவரின் படைப்புகளை உரைகள்,ஒளிஒலி,புகைபட கோப்புகளை  creative commons படைப்பாக்க பொதுமங்கள்  உரிமையில் வெளியிடுமாறு கணியம் அறக்ட்டளை சார்பாக வேண்டுகோள் விடுக்கபட்டது விரைவில் அறிவிப்பை வெளியிட இசைவு தந்துள்ளார். இப்பணியை கலீல்ஜாக்கீர் அவரிடம் கொடுக்கபட்டுள்ளது.

![image](https://user-images.githubusercontent.com/38220354/56080017-5ed93f80-5e19-11e9-9c91-071bd767306d.png)

![photo_2019-04-13_15-35-36](https://user-images.githubusercontent.com/38220354/56080044-96e08280-5e19-11e9-9711-8ce19a881b7e.jpg)
![photo_2019-04-13_15-30-40](https://user-images.githubusercontent.com/38220354/56080046-9e079080-5e19-11e9-9b02-61b6f29a2c06.jpg)

**Comment by khaleeljageer** [comment]
புத்தகங்களின் உரிமத்தை Creative Commons-ல் வெளியிடுவதில் அவருக்கு சிரமம் உள்ளதால் மறுத்துவிட்டார்.
